-- =========================
-- SCHEMA POSTGRESQL
-- Database: monitoring_panen
-- =========================

BEGIN;

-- Tabel kecamatan
CREATE TABLE kecamatan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kecamatan VARCHAR(50)
);

-- Tabel desa
CREATE TABLE desa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kecamatan INTEGER,
    nama_desa VARCHAR(100) NOT NULL,
    CONSTRAINT fk_desa_kecamatan
        FOREIGN KEY (id_kecamatan)
        REFERENCES kecamatan(id)
);

-- Tabel users
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    nama_lengkap VARCHAR(100),
    no_hp VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    role VARCHAR(20) DEFAULT 'pcl',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    pml_id INTEGER
);

-- Tabel segmen
CREATE TABLE segmen (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_segmen VARCHAR(9) UNIQUE NOT NULL
);

-- Tabel monitoring_data_panen
CREATE TABLE monitoring_data_panen (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_petani VARCHAR(100) NOT NULL,
    desa VARCHAR(100) NOT NULL,
    kecamatan VARCHAR(100) NOT NULL,
    tanggal_panen DATE NOT NULL,
    subround INTEGER NOT NULL,
    foto_serah_terima VARCHAR(255) NOT NULL,
    foto_bukti_plot_ubinan VARCHAR(255) NOT NULL,
    foto_berat_timbangan VARCHAR(255) NOT NULL,
    berat_plot DECIMAL(10,2),
    gkp DECIMAL(10,2),
    gkg DECIMAL(10,2),
    ku DECIMAL(10,2),
    status VARCHAR(20) DEFAULT 'belum selesai',
    user_id INTEGER NOT NULL,
    nomor_segmen VARCHAR(9) NOT NULL,
    nomor_sub_segmen VARCHAR(2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    note_revisi TEXT,
    revised_at TIMESTAMP,
    revised_by VARCHAR(100),
    CONSTRAINT fk_monitoring_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

COMMIT;
